### ISSUE TITLE
Cannot quit

### ISSUE THREAD

**Issue by probonopd** [sgtaziz/RemoteMessages-Client#1]
When I run the AppImage, it asks me for IP Address and Port Number without any further information or explanation. Since I don't know them, I want to quit the app, which is impossible. There is no obvious way to quit it from that window or the menu bar. Even clicking the X to close the window doesn't quit the app.

**Comment by sgtaziz** [comment]
This is the intended behavior since the app is supposed to run in the background. To quit it, you can right click the icon in your dock and there should be a quit option.

**Comment by probonopd** [comment]
Thanks for the explanation. It would be good if the window would tell me what IP Address and Port Number to enter or where to get this information from...

**Comment by sgtaziz** [comment]
You can find that information inside Settings->Remote Messages from your phone. (You need the Remote Messages tweak installed from the BigBoss repo)
