### ISSUE TITLE
[Bug] NetworkError when iPhone is asleep

### ISSUE THREAD

**Issue by cradcore** [sgtaziz/RemoteMessages-Client#10]
If my iPhone is locked and the screen is off, about 90% of the time when I try and send a message, it will result in a NetworkError. As soon as I tap the iPhone screen, the messages will start working again

**Comment by sgtaziz** [comment]
Is this intended for RemoteMessages or WebMessage?

**Comment by cradcore** [comment]
@sgtaziz My bad, it is for WebMessage
