### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Xikre** [sgtaziz/RemoteMessages-Client#2]
When I open RemoteMessages-Client (Windows _and_ Linux) I put in the correct info (IP & port) and the window is just white.

**Comment by sgtaziz** [comment]
This is because it's not able to establish a connection to the server. I'm currently building the fix I applied which should help out. A user on reddit also suggested exiting Remote Messages from your browser if you have it open then restart the app.

**Comment by sgtaziz** [comment]
https://github.com/sgtaziz/RemoteMessages-Client/commit/d9de50a1904b444027bb67c99c38bf1218ff2920

This commit should fix white screen bug when using authentication.
