### ISSUE TITLE
iTunnel

### ISSUE THREAD

**Issue by Xikre** [sgtaziz/RemoteMessages-Client#3]
So I've been using iTunnel to use RemoteMessages on my desktop which has no WiFi, so I've been putting 127.0.0.1:(port) into my browser to use RemoteMessages. However,  the RemoteMessages-Client doesn't pick up on that and thus, cannot connect, even though the browser can.

**Comment by sgtaziz** [comment]
I'll double check this and see what I can do to fix

**Comment by sgtaziz** [comment]
This should be fixed with the latest 1.0.4 release.
https://github.com/sgtaziz/RemoteMessages-Client/commit/ad0ed434d1026d150b76515bb7396bf7d0a6136c

**Comment by Xikre** [comment]
I'll test it out tomorrow! Thanks!

**Comment by Xikre** [comment]
Worked!

**Comment by sgtaziz** [comment]
Glad to hear :)
