### ISSUE TITLE
Linux/Ubuntu Issue

### ISSUE THREAD

**Issue by Xikre** [sgtaziz/RemoteMessages-Client#4]
So I have yet to try this on my desktop today, but I tried it on my Ubuntu laptop and it says my IP/port info is incorrect, even thought it is. This is the latest version (1.0.4)
![2016-10-09 11 40 08](https://cloud.githubusercontent.com/assets/22685418/19222804/7f5e9998-8e15-11e6-9e30-84586693cf0e.jpg)
![screenshot from 2016-10-09 11-43-49](https://cloud.githubusercontent.com/assets/22685418/19222814/b257dcb0-8e15-11e6-849f-cade643dc99b.png)

**Comment by sgtaziz** [comment]
Are you able to access it from the browser?

**Comment by Xikre** [comment]
I couldn't, so I merely restarted RemoteMessages and I was able to connect.
