### ISSUE TITLE
[Feature Request] Notifications when minimized only

### ISSUE THREAD

**Issue by fletchto99** [sgtaziz/RemoteMessages-Client#5]
Would it be possible to have the option only show notifications if the application is minimized to the task tray?

**Comment by sgtaziz** [comment]
Definitely is. I'll look into it as soon as I have time, midterms are coming up this week though so might not be as quick as you expect.

**Comment by fletchto99** [comment]
@sgtaziz I understand completely. I too have 3 midterms this week. If you want I could look implementing this sometime next week during my reading week.

**Comment by sgtaziz** [comment]
@fletchto99 gotta love college life, good luck with your midterms! And feel free to look into it if you'd like, I'll probably have time to get started on it sometime this weekend.

**Comment by fletchto99** [comment]
Closing as I no longer have a jailbroken phone :)
